### PR TITLE
Make project buildable with Gradle

### PR DESCRIPTION
**Pull request by milesgould**
Since `elasticsearch-java-client` and `flexi-gson` are dependencies of some of the `open-code` libraries and depend on others, I've imported their history into this repo using `git-subtree`. This means that this PR is unavoidably vast. However, very little of the code here is new. Only the following commits need to be reviewed:

 - 06a06b51 (Gradlify flexi-gson)
 - 551602ee (Gradlify es-java-client)
 - 5dd60f57, 56ffc970, 09c46fdf (fix various flaky tests)
 - fcf293f0 (Gradlify the rest of the project)

### CODE REVIEW

**Comment by winterstein** [comment]
Hello @DanielRobertAppel 

Could you have a look at this?

This is a PR from Miles. Its doing some git engineering, which I don't fully understand.

Miles end goal was to get WW code into the ZF mega-repo via a git subtree. 

This PR includes the flexi-gson and ESJC repos into the open-code repo, using subtree in some way. I'm not sure of exactly how, or what effect that has for ongoing development. 

We want to keep separate repos, rather than make one mega-repo. I'm also wary of adding unnecessary git subtree complexity.

Thanks,
 - Daniel

**Comment by DanielRobertAppel** [comment]
Hello @milesgould ,  I am attempting to come to grips with what is happening here.  My understanding is that you've tried to make the fully fledged and separate repositories of elasticsearch-java-client and flexi-gson  as subtrees of the open-code repository.  Is that correct?

**Comment by milesgould** [comment]
@DanielRobertAppel yes, that's right. I found that the three repos couldn't be built from scratch separately - flexi-gson and ESJC depend on winterwell.utils, and (for instance) winterwell.datalog depends on flexi-gson and ESJC. So I think it makes sense from a build-system perspective to combine the repos, though this is not the only way of doing so.

**Comment by DanielRobertAppel** [comment]
@milesgould , I see.  I agree with you regarding the inter-connected-ness and dependency-needs of each project.  You are correct, these repos are inter-dependent upon each other.  And from a build-perspective it makes for much fewer steps involved for a continuous integration system.

On our side of things, we want these individual project-repositories to remain separate --- meaning, each project has it's own separate git history, and git repository.  Full disclosure : we do not know if this is how you have set them up using git-subtrees or not.  We do not fully grasp the capabilities of the subtree-ing .  We simply saw a merge-action and it caused us to start to question if the projects would remain independently-interdependent of each other.

**Comment by milesgould** [comment]
@DanielRobertAppel OK, I see. This change merges all three repos into one (preserving history): in theory it should be possible to take changes made here and merge them back into the upstream ESJC and flexi-gson repos, but in practice we've found that `git subtree` doesn't do that as well as the docs advertise. So yes, if you're set on keeping open-code, ESJC and flexi-gson as three separate-but-inderdependent repos, you should not merge this PR, and I should find some other way to submit my changes upstream. Can I ask what benefit you get from keeping the repos separate?

**Comment by winterstein** [comment]
Hello @milesgould 

> Can I ask what benefit you get from keeping the repos separate?

It's to follow the github "standard" approach of: one repo = one project.    
Advantages: it's better for if people want to draw on the code in a modular way. It allows for projects to evolve separately.

Also, flexi-gson ought to be a fork of the official Google gson repo. The only reason it isn't, is because Google didn't use git back when I made it. I'd like to make flexi-gson into a fork of the official gson repo. That would have the advantage of supporting upstream changes from Google. There's been a major version upgrade, so it's a bit more work than it looks.

So the anomaly is the open-code repo, where we took 10 projects and put them in the one repo. That was because historically they came from one internal private repo. And also it was slightly less setup work.

If you look at the project level, the circular dependencies go away. E.g. flexi-gson depends on ww.utils -- which doesn't depend on flexi-gson. It's a DAG.

Re. build-system -- you have the build.gradle files at the project level. Does that make the build independent from how the git subtree repos are organised?

**Comment by winterstein** [comment]
Options?

1. Add flexi-gson and ESJC to open-code.    
I'd prefer not to because (a) flexi-gson ought to fork off from official-gson, (b) ESJC branches & versioning should be independent to match ES, and (c) the one repo = one project paradigm is the standard.

2. Alter open-code splitting it into 10 repos, to get one repo = one project, and alter the ZoneFox subtree setup to match, with one subtree per repo.

3. Leave open-code as-is, but alter the ZoneFox subtree setup to have separate subtrees for ESJC and flexi-gson.

4. Leave open-code as-is and ZoneFox as-is, and handle upstream edits manually, via cherry-picking patches with tweaks, or meld.

5. Other options I haven't thought of.

@milesgould @DanielRobertAppel - What do you think?
Thanks, Dan

**Pull request closed without merging**
